Feature/dx 1626 design adjustments
SwedbankPay/swedbank-pay-design-guide-jekyll-theme pull request #620
Opened 2022-02-01 13:31 UTC by trieutran91

2022-02-01 13:48 UTC, asbjornu requested changes

2022-02-01 13:48 UTC, asbjornu commented on _includes/github.html
> +    id="github" class="github" target="_blank"
If we add `id="github"` I suppose we can remove `class="github"`?

```suggestion
    id="github" target="_blank"
```

2022-02-01 13:48 UTC, asbjornu commented on _sass/title-header.scss
> +    }
Just cram this into the `#github` selector instead?

```suggestion
```

2022-02-01 14:09 UTC, trieutran91 commented
These changes allows us to use the Github logo with white background and black cat, and the inverse.
The logo with white background works better on a dark background such as https://developer.swedbankpay.com/payment-instruments/.
While the logo with black background works on the pages with the new design such as https://developer.stage.swedbankpay.com/.

Can this work until we have worked out a design for the whole page?

2022-02-01 14:46 UTC, asbjornu commented
Hm. I'm not sure that we can maintain both black on white and white on black octocats simultaneously. When the theme is upgraded, all pages on the Developer Portal will make use of the new theme, it can't be conditioned. So it's an all or nothing approach where we either make it work black on white or white on black. Unless there's something I've missed?

2022-02-01 15:03 UTC, trieutran91 commented
Well, we have a different design on the front page/Checkout v3 and the rest of the portal. 
Front page/Checkout v3 have a white header, while the other pages have the dark brown header ref https://developer.stage.swedbankpay.com/checkout-v2/payment-menu.
I believe that one of the arguments behind that decision was to separate the new Checkout v3 somehow. But yeah, it is not adequate.

2022-02-01 23:08 UTC, asbjornu commented
Hm, I think we're both right somehow. We don't need both `class="github"` and `id="github"`, but the placement of the different selectors you've added and modified is correct, since they then apply to different parts of the portal. I think if you just change the `.github` selector to `#github` and remove `class="github"`, it should work. But please test it.

2022-02-02 00:14 UTC, trieutran91 commented
> Hm, I think we're both right somehow. We don't need both `class="github"` and `id="github"`, but the placement of the different selectors you've added and modified is correct, since they then apply to different parts of the portal. I think if you just change the `.github` selector to `#github` and remove `class="github"`, it should work. But please test it.

It worked! I did not manage to wrap my head around that the placement of the selectors where enough to apply for different parts. No need for `class="github"` indeed!

2022-02-02 11:37 UTC, asbjornu approved these changes

2022-02-02 13:07 UTC, merged